import summary from './landing-summary.json';

/**
 * What the landing page is allowed to import.
 *
 * Deliberately a separate module from data/conjunctions and data/objects. Those
 * two pull the whole engine — 632 kB of committed screening result, plus
 * satellite.js running the TLE parse at import time — and the marketing page
 * needs three scalars and six numbers per object. Importing them here would
 * quietly undo the split, so nothing in this file reaches for them.
 *
 * Regenerated by scripts/landing-summary.ts as part of `npm run screen`, from
 * the same committed run the console shows. Every figure below is measured.
 */

export interface HeroObject {
  /** Mean altitude, km. */
  a: number;
  /** Inclination, degrees. */
  i: number;
  /** Right ascension of the ascending node, degrees. */
  r: number;
  /** Mean anomaly at the snapshot epoch, degrees. */
  m: number;
  /** Orbital period, minutes. */
  p: number;
  /** 1 for debris. */
  d: number;
}

export const LANDING = summary;
export const HERO_OBJECTS: HeroObject[] = summary.objects;
export const SNAPSHOT_EPOCH_MS = summary.snapshotEpochMs;
